# -*- coding: utf-8 -*-
"""chatterbot with corpus package.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_VhrvXdF73WjoqscGaDgc3LQuL4Dl1Es
"""

pip install chatterbot

pip install chatterbot-corpus

import os 
# import chatterbot
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer

bot = ChatBot("Lohith")
# trainer = ListTrainer(bot)

trainer = ChatterBotCorpusTrainer(bot)

trainer.train(
    "chatterbot.corpus.english"
)

# Train the chatbot based on the english corpus
trainer.train("chatterbot.corpus.english")

#for files in os.listdir('/Users/Desu.Lohith/Desktop/Intern/chatterbotenglish/'):
 #data = open('/Users/Desu.Lohith/Desktop/Intern/chatterbotenglish/'+ files, 'r').readlines()
 #bot.train(data)

while True:
    message = input("You: ")
    if message.strip().lower() != "bye" or message.strip().lower() =="tata":
        reply = bot.get_response(message)
        print("Lohith: ",reply)
    elif message.strip().lower() =="bye" or message.strip().lower() =="tata":
        print("okay")
        break



